# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99ac6a2e9abf7e9876e87388a97f6d06de1da2e0a853d9e187e51504973c465cc02561e7669c468ec16754ca4465ebf164f0f64b91563bee603e68b39afe275

test:
  secret_key_base: 4cba29c63726171d599a2324f6cc7e51fe6f9dbc9086f468970de8be5d15375411f0385d636b7801a2613286c7e0d55626cd7965b75380d82d8de76bc8e7f092

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
